import PDFDocument from "pdfkit";

interface PDFExportData {
  matchScore: number;
  strengths: string[];
  missingKeywords: string[];
  weakAreas: string[];
  resumeImprovements: string[];
  summary: string;
  questions: { type: string; question: string }[];
  guidance: { questionId: string; keyPoints: string[]; dontForget: string[] }[];
  jobCategory?: string;
}

export async function generateReportPDF(data: PDFExportData): Promise<Buffer> {
  const doc = new PDFDocument({ margin: 50, size: "A4" });
  const buffers: Buffer[] = [];

  doc.on("data", (chunk: Buffer) => buffers.push(chunk));

  return new Promise((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    // Header
    doc.fontSize(24).font("Helvetica-Bold").text("PrepFit Report", { align: "center" });
    doc.fontSize(12).font("Helvetica").fillColor("#6B7280");
    doc.text("Interview Preparation Analysis", { align: "center" });
    if (data.jobCategory) {
      doc.text(`Category: ${data.jobCategory}`, { align: "center" });
    }
    doc.moveDown(1.5);

    // Match Score
    doc.fontSize(32).font("Helvetica-Bold").fillColor("#111827");
    doc.text(`${data.matchScore}%`, { align: "center" });
    doc.fontSize(12).font("Helvetica").fillColor("#6B7280");
    doc.text("Match Score", { align: "center" });
    doc.moveDown(1);

    // Summary
    doc.fontSize(11).font("Helvetica").fillColor("#111827");
    doc.text(data.summary, { width: doc.page.width - 100, align: "center" });
    doc.moveDown(1.5);

    // Section helper
    const section = (title: string) => {
      doc.fontSize(14).font("Helvetica-Bold").fillColor("#111827");
      doc.text(title);
      doc.moveDown(0.5);
    };

    // Strengths
    section("Strengths");
    doc.fontSize(10).font("Helvetica").fillColor("#374151");
    data.strengths.forEach((s) => doc.text(`  • ${s}`));
    doc.moveDown(1);

    // Weak Areas
    section("Weak Areas");
    doc.fontSize(10).font("Helvetica");
    data.weakAreas.forEach((w) => doc.text(`  • ${w}`));
    doc.moveDown(1);

    // Missing Keywords
    section("Missing Keywords");
    doc.fontSize(10).font("Helvetica");
    doc.text(`  ${data.missingKeywords.join(", ")}`);
    doc.moveDown(1);

    // Resume Improvements
    section("Resume Suggestions");
    doc.fontSize(10).font("Helvetica");
    data.resumeImprovements.forEach((r, i) => doc.text(`  ${i + 1}. ${r}`));
    doc.moveDown(1);

    // Interview Questions
    section("Likely Interview Questions");
    data.questions.forEach((q, i) => {
      doc.fontSize(10).font("Helvetica-Bold").fillColor("#111827");
      doc.text(`Q${i + 1} [${q.type}]: ${q.question}`);
      const guide = data.guidance.find((g: any) => g.questionId === `q${i + 1}`);
      if (guide) {
        doc.fontSize(9).font("Helvetica").fillColor("#6B7280");
        doc.text(`  Key points: ${guide.keyPoints.join("; ")}`);
      }
      doc.moveDown(0.3);
    });

    doc.moveDown(1);
    doc.fontSize(9).font("Helvetica").fillColor("#9CA3AF");
    doc.text("Generated by PrepFit — Prepare for interviews faster.", { align: "center" });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: "center" });

    doc.end();
  });
}
